version: '3.8'

services:
  cep-gateway:
    build: ./cep-gateway
    container_name: cep-gateway
    ports:
      - "8080:8080"
    environment:
      - WEATHER_ENGINE=http://weather-engine:8081
    depends_on:
      - weather-engine

  weather-engine:
    build: ./weather-engine
    container_name: weather-engine
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4318:4318"